import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {BETA_PROGRAM} from '../src/data/beta-program.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=JSON.parse(fs.readFileSync(path.join(root,'data/beta-program.json'),'utf8'));
const req=(value,message)=>{if(!value)throw new Error(message)};
req(data.schemaVersion===1,'beta schema');
req(data.contentVersion==='1.0.0','beta content version');
req(data.channel==='closed-beta','beta channel');
req(data.localOnly===true&&data.telemetryDefault===false,'privacy defaults');
req(data.privacy.networkTransmission===false&&data.privacy.manualExportOnly===true,'privacy contract');
req(data.acceptance.releaseGateMustRemainBlocked===true,'release gate contract');
req(BETA_PROGRAM.deviceMatrix.length>=6,'device matrix');
req(BETA_PROGRAM.checklist.length>=10,'manual checklist');
req(BETA_PROGRAM.categories.includes('mobile-scroll'),'mobile scroll category');
const app=fs.readFileSync(path.join(root,'src/app.js'),'utf8');
for(const token of ['function beta()','runBetaAudit','exportBetaFeedback','medsim-beta-sessions-v027','localTelemetry'])req(app.includes(token),`app token ${token}`);
console.log(JSON.stringify({ok:true,channel:data.channel,devices:BETA_PROGRAM.deviceMatrix.length,checklist:BETA_PROGRAM.checklist.length,telemetryDefault:data.telemetryDefault,networkTransmission:data.privacy.networkTransmission}));
