const BUILD={version:'0.5.0',stamp:'20260424_2028',label:'v0.5.0 | build 2026-04-24 20:28'};
const A='assets/';
const bg=n=>`${A}backgrounds/background_${String(n).padStart(2,'0')}.png`;
const av=n=>`${A}avatars/avatar_${String(n).padStart(2,'0')}.png`;
const ui=n=>`${A}ui/ui_${String(n).padStart(2,'0')}.png`;
const app=document.querySelector('#app');
const saveKey='medsim-vale-save-v050';
const fresh=()=>({screen:'setup',drawer:false,sound:true,selectedSpec:'clinica-medica',currentCase:0,score:null,timeline:[],actions:{questions:[],exams:[],procedures:[],hypotheses:[],conduct:[]},player:{name:'Dr. Rafael Santos',short:'Dr. Rafael',avatar:1,level:1,xp:0,credits:2450,reputation:'Boa',patients:0,correct:88,highScoreCases:0,learnedModules:0,title:'Interno',rank:1248,streak:0},simulation:{minutes:720,criticality:0},unlocks:{specialties:['clinica-medica']},missions:{claimed:[]},completed:[]});
let state=JSON.parse(localStorage.getItem(saveKey)||'null')||fresh();
const save=()=>localStorage.setItem(saveKey,JSON.stringify(state));
let audioCtx=null;
function sound(type='tap'){if(!state.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);const map={tap:[520,.025],ok:[760,.055],warn:[210,.09],nav:[390,.04],level:[880,.14]};const [f,d]=map[type]||map.tap;o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.045,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.start();o.stop(audioCtx.currentTime+d+.01)}catch(e){}}
function toast(t,type='ok'){sound(type);let e=document.createElement('div');e.className='toast pop';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2100)}
function go(s){sound('nav');state.screen=s;state.drawer=false;save();render()}
const exams=['Hemograma completo','Eletrocardiograma (ECG)','Raio-X de tórax','Glicemia de jejum','Perfil lipídico','Troponina','Ureia e Creatinina','TSH','Urina tipo 1','Urocultura'];
const procedures=['Aferir sinais vitais','Exame físico geral','Ausculta cardíaca','Ausculta pulmonar','Palpação abdominal','Avaliação neurológica','Solicitar acesso venoso','Orientação terapêutica'];
const hypotheses=['Hipertensão Arterial Estágio 1','Angina estável','Ansiedade','Refluxo gastroesofágico','Cefaleia tensional','ITU não complicada'];
const conducts=['orientar estilo de vida','monitorar pressão','retorno ambulatorial','analgesia simples','higiene do sono','ECG seriado','estratificação de risco','antibioticoterapia guiada','hidratação','encaminhar cardiologia'];
const patients=['Carlos Eduardo','Maria Aparecida','João Victor','Fernanda Lima','Luís Fernando','Ana Clara','Marcos Vinícius','Patrícia Gomes','Gabriel Alves','Beatriz Souza','Rafael Moreira','Juliana Costa','Thiago Martins','Ricardo Andrade','Vanessa Oliveira','Mateus Lima','Camila Ferreira','Daniel Rios','Isabela Nunes','André Souza'];
const cases=[
{id:'hipertensao-1',specialty:'clinica-medica',patient:'Marcos Vinícius',age:34,sex:'Masculino',profession:'Analista de Sistemas',complaint:'cefaleia frequente, cansaço e aperto no peito às vezes',vitals:[['PA','128/82','mmHg'],['FC','88','bpm'],['FR','18','irpm'],['TEMP.','36,7','°C'],['SpO₂','98','%']],correctQuestions:['tempo dos sintomas','histórico familiar','dor em esforço'],correctExams:['Eletrocardiograma (ECG)','Perfil lipídico','Glicemia de jejum'],correctProcedures:['Aferir sinais vitais','Exame físico geral','Ausculta cardíaca'],diagnosis:'Hipertensão Arterial Estágio 1',idealConduct:['orientar estilo de vida','monitorar pressão','retorno ambulatorial'],xp:160},
{id:'cefaleia-tensional',specialty:'clinica-medica',patient:'Patrícia Gomes',age:29,sex:'Feminino',profession:'Professora',complaint:'dor de cabeça em aperto no fim do dia, sem febre e sem vômitos',vitals:[['PA','118/76','mmHg'],['FC','78','bpm'],['FR','16','irpm'],['TEMP.','36,5','°C'],['SpO₂','99','%']],correctQuestions:['tempo dos sintomas','estresse e sono','sinais de alarme'],correctExams:['Hemograma completo'],correctProcedures:['Aferir sinais vitais','Exame físico geral','Avaliação neurológica'],diagnosis:'Cefaleia tensional',idealConduct:['analgesia simples','higiene do sono'],xp:130},
{id:'angina-estavel',specialty:'cardiologia',patient:'Ricardo Andrade',age:56,sex:'Masculino',profession:'Motorista',complaint:'aperto no peito aos esforços que melhora ao repousar',vitals:[['PA','142/88','mmHg'],['FC','92','bpm'],['FR','19','irpm'],['TEMP.','36,6','°C'],['SpO₂','97','%']],correctQuestions:['dor em esforço','irradiação da dor','fatores de risco'],correctExams:['Eletrocardiograma (ECG)','Troponina','Perfil lipídico'],correctProcedures:['Aferir sinais vitais','Ausculta cardíaca','Solicitar acesso venoso'],diagnosis:'Angina estável',idealConduct:['ECG seriado','estratificação de risco','encaminhar cardiologia'],xp:190},
{id:'itu-nao-complicada',specialty:'clinica-medica',patient:'Vanessa Oliveira',age:38,sex:'Feminino',profession:'Gerente',complaint:'ardência para urinar, aumento da frequência urinária e desconforto baixo ventre',vitals:[['PA','116/74','mmHg'],['FC','84','bpm'],['FR','17','irpm'],['TEMP.','37,2','°C'],['SpO₂','99','%']],correctQuestions:['dor lombar','febre recente','gestação'],correctExams:['Urina tipo 1','Urocultura'],correctProcedures:['Aferir sinais vitais','Palpação abdominal'],diagnosis:'ITU não complicada',idealConduct:['antibioticoterapia guiada','hidratação'],xp:145}
];
const specs=[['clinica-medica','Clínica Médica','Avalie, diagnostique e trate condições clínicas diversas.','⚕',14,bg(9),1],['urgencia','Urgência e Emergência','Atenda casos críticos e tome decisões que salvam vidas.','✚',15,bg(8),2],['cardiologia','Cardiologia','Avalie e trate doenças do coração e sistema circulatório.','❤️',12,bg(4),3],['pediatria','Pediatria','Cuide da saúde das crianças e adolescentes.','👶',9,bg(11),4],['dermatologia','Dermatologia','Diagnostique e trate condições da pele, cabelos e unhas.','🧴',10,bg(5),5],['urologia','Urologia','Cuide da saúde do sistema urinário e reprodutor.','🩺',8,bg(6),6],['ginecologia','Ginecologia','Acompanhe a saúde da mulher em todas as fases.','♀',10,bg(7),6],['ambulatorio','Ambulatório','Atendimento geral e acompanhamento de rotina.','🏥',9,bg(10),1],['outras','Outras Especialidades','Acesso futuro a novas áreas e especialidades.','+',0,bg(3),99]];
const missionBank=[{id:'daily-3-patients',type:'Diária',title:'Atender 3 pacientes',metric:'patients',goal:3,rewardXp:120,rewardCredits:80},{id:'daily-accuracy',type:'Diária',title:'Fechar 2 casos com score acima de 80',metric:'highScoreCases',goal:2,rewardXp:160,rewardCredits:100},{id:'weekly-study',type:'Semanal',title:'Concluir 3 módulos de aprendizagem',metric:'learnedModules',goal:3,rewardXp:300,rewardCredits:200}];
function xpNeed(l){return 500+(l-1)*420}function syncProgress(){let p=state.player,lvl=1,spent=p.xp;while(spent>=xpNeed(lvl)&&lvl<20){spent-=xpNeed(lvl);lvl++}p.level=lvl;p.title=p.xp>=4200?'Especialista Vale':p.xp>=2600?'Médico Clínico':p.xp>=1400?'Residente R2':p.xp>=600?'Residente R1':'Interno';state.unlocks=state.unlocks||{specialties:['clinica-medica']};[['urgencia',2],['cardiologia',3],['pediatria',4]].forEach(x=>{if(p.level>=x[1]&&!state.unlocks.specialties.includes(x[0]))state.unlocks.specialties.push(x[0])});p.rank=Math.max(1,1248-Math.floor(p.xp/8)-(p.highScoreCases||0)*12);return{spent,next:xpNeed(lvl),pct:Math.min(100,Math.round(spent/xpNeed(lvl)*100))}}
function rep(sc){return sc>=90?'Excelente':sc>=78?'Boa':sc>=62?'Instável':'Em observação'}
function activeCase(){return cases[state.currentCase%cases.length]}function selected(type,val){return state.actions[type].includes(val)}
function addTime(kind){const cost={questions:3,exams:9,procedures:5,hypotheses:2,conduct:4}[kind]||2;state.simulation.minutes=Math.max(0,state.simulation.minutes-cost);if(kind==='exams'&&state.actions.exams.length>3)state.simulation.criticality+=2}
function toggleAction(type,val){let arr=state.actions[type];if(arr.includes(val)){state.actions[type]=arr.filter(x=>x!==val);toast('Ação removida','tap')}else{arr.push(val);state.timeline.push({t:minToClock(),text:val});addTime(type);toast('Ação registrada','ok')}save();render()}
function minToClock(){let m=720-state.simulation.minutes;let h=8+Math.floor(m/60),mi=m%60;return `${String(h).padStart(2,'0')}:${String(mi).padStart(2,'0')}`}
function count(a,b){return a.filter(x=>b.includes(x)).length}function calcScore(){const c=activeCase();let q=count(state.actions.questions,c.correctQuestions),e=count(state.actions.exams,c.correctExams),pr=count(state.actions.procedures,c.correctProcedures),co=count(state.actions.conduct,c.idealConduct);let diag=state.actions.hypotheses.includes(c.diagnosis)?25:0;let excess=Math.max(0,state.actions.exams.length-c.correctExams.length)*6;let missingConduct=Math.max(0,c.idealConduct.length-co)*4;return Math.max(15,Math.min(100,Math.round(q*6+e*7+pr*5+co*6+diag+10-excess-missingConduct-state.simulation.criticality)))}
function finishCaseCore(){const c=activeCase(),sc=calcScore();state.score=sc;state.completed.push({id:c.id,score:sc,at:BUILD.label});state.player.xp+=Math.round(c.xp*(sc/100));state.player.credits+=sc>=80?110:60;state.player.patients++;if(sc>=80)state.player.highScoreCases++;state.player.streak=sc>=75?state.player.streak+1:0;state.player.correct=Math.round((state.player.correct+sc)/2);state.player.reputation=rep(sc);state.currentCase=(state.currentCase+1)%cases.length;syncProgress();save();go('post')}
function missionProgress(m){return Math.min(m.goal,state.player[m.metric]||0)}function canClaim(m){return missionProgress(m)>=m.goal&&!state.missions.claimed.includes(m.id)}function claimMission(id){let m=missionBank.find(x=>x.id===id);if(!m||!canClaim(m))return toast('Missão ainda não concluída','warn');state.missions.claimed.push(id);state.player.xp+=m.rewardXp;state.player.credits+=m.rewardCredits;syncProgress();save();toast('Recompensa coletada!','level');render()}
function logo(){return `<div class="brand"><div class="pulse-line"></div><div class="logo"><span>Simulador de</span><b>Medicina</b></div><small>VALE EDITION • MODO SIMULADOR</small></div>`}
function profile(){let p=state.player,pr=syncProgress();return `<div class="profile panel"><img src="${av(p.avatar)}"><div><strong>${p.name}</strong><em>${p.title} • Nível ${p.level}</em><div class="xp"><i style="width:${pr.pct}%"></i></div><small>${pr.spent} / ${pr.next} XP • Rep. ${p.reputation}</small></div></div>`}
function top(section){return `<header class="topbar">${logo()}<button class="hamb" onclick="toggleDrawer()">☰</button><h2>${section}</h2>${profile()}</header>`}
function shell(section,body,bgNum=8){return `<main class="screen fade" style="--bg:url('${bg(bgNum)}')">${top(section)}${body}<div class="build">${BUILD.label}</div></main>`}
function sidebar(active){let items=[['hub','🏠','Lobby','Visão geral'],['learning','📖','Aprendizagem','Procedimentos'],['specialty','🩺','Plantão','Especialidades'],['settings','⚙️','Configurações','Sistema']];return `<aside class="side panel ${state.drawer?'open':''}">${items.map(x=>`<button onclick="go('${x[0]}')" class="nav ${active==x[0]?'active':''}"><span>${x[1]}</span><b>${x[2]}</b><small>${x[3]}</small></button>`).join('')}</aside><div class="shade ${state.drawer?'show':''}" onclick="toggleDrawer()"></div>`}
function setup(){app.innerHTML=`<main class="screen fade" style="--bg:url('${bg(1)}')">${logo()}<img class="hero-doc" src="${av(state.player.avatar)}"><section class="setup panel pop"><h3>🫀 NOVO GAME</h3><h2>1. Escolha seu avatar</h2><div class="avatar-row">${[1,2,3,4,5].map(i=>`<button class="avatar-choice ${state.player.avatar==i?'active':''}" onclick="pickAvatar(${i})"><img src="${av(i)}"></button>`).join('')}</div><h2>2. Nome do personagem</h2><input class="input" id="name" value="${state.player.name}"><h2>3. País de origem</h2><select class="input"><option>🇧🇷 Brasil</option></select><button class="btn primary" onclick="startGame()">🫀 Continuar</button></section><div class="build">${BUILD.label}</div></main>`}
function menu(){app.innerHTML=`<main class="screen fade" style="--bg:url('${bg(2)}')">${logo()}<section class="welcome slide"><h1>Bem-vindo,<br><span>${state.player.short}</span></h1><p>O conhecimento é a sua maior ferramenta. Cada decisão pode mudar uma vida.</p></section><section class="mode-grid"><article class="mode card" style="--cardbg:url('${bg(3)}')"><h2>Modo Carreira</h2><p>Progressão real, reputação, missões e desbloqueios.</p><button class="btn primary" onclick="go('hub')">Entrar</button></article><article class="mode card" style="--cardbg:url('${bg(7)}')"><h2>Modo Simulador</h2><p>Casos mais rigorosos, tempo clínico e penalidade por excesso de exames.</p><button class="btn" onclick="go('specialty')">Praticar</button></article></section><div class="build">${BUILD.label}</div></main>`}
function hub(){let p=state.player,pr=syncProgress();app.innerHTML=shell('LOBBY DO RESIDENTE',`<div class="layout">${sidebar('hub')}<section class="maincol"><div class="hero-card card" style="--cardbg:url('${bg(8)}')"><h1>Bem-vindo, ${p.short}</h1><p>Fase 5 ativa: progressão, retenção, missões, reputação e desbloqueios.</p><div class="level medallion">${p.level}</div><div class="stats"><div>🏆<b>${p.xp}</b><small>XP total</small></div><div>🌐<b>#${p.rank}</b><small>Ranking local</small></div><div>👥<b>${p.patients}</b><small>Pacientes</small></div><div>🎯<b>${p.correct}%</b><small>Acerto</small></div></div></div><div class="two"><div class="card"><h3>Progresso da carreira</h3><p>${p.title} • Reputação ${p.reputation}</p><div class="xp big"><i style="width:${pr.pct}%"></i></div><p>${pr.spent} / ${pr.next} XP • Desbloqueadas: ${state.unlocks.specialties.join(', ')}</p><button class="btn primary" onclick="go('specialty')">Iniciar plantão</button></div><div class="card"><h3>Últimos casos</h3>${state.completed.slice(-4).reverse().map(x=>`<p>✅ ${x.id} <b>${x.score}/100</b></p>`).join('')||'<p>Nenhum caso concluído nesta build.</p>'}</div></div></section><aside class="rightcol"><div class="card"><h3>Missões e recompensas</h3>${missionBank.map(m=>`<div class='mission'><b>${m.type}</b><span>${m.title}</span><small>${missionProgress(m)} / ${m.goal}</small><button class='btn mini' onclick="claimMission('${m.id}')" ${canClaim(m)?'':'disabled'}>Coletar</button></div>`).join('')}</div><div class="card"><h3>Economia</h3><h2>${p.credits} créditos</h2><p>Base pronta para loja futura, cosméticos e packs.</p></div></aside></div>`,8)}
function specialty(){app.innerHTML=shell('PLANTÃO — ESPECIALIDADE',`<div class="layout">${sidebar('specialty')}<section class="maincol"><h1>Escolha sua especialidade</h1><p class="muted">Modo simulador: especialidades desbloqueiam por nível.</p><div class="specialties">${specs.map(s=>{let locked=state.player.level<s[6];return `<article class="spec card ${locked?'locked':''}" onclick="${locked?`toast('Desbloqueia no nível ${s[6]}','warn')`:`state.selectedSpec='${s[0]}';go('shift')`}"><img src="${s[5]}"><span>${s[3]}</span><h2>${s[1]}</h2><p>${s[2]}</p><b>${locked?'Bloqueada • nível '+s[6]:'Disponível'}</b></article>`}).join('')}</div></section><aside class="rightcol"><div class="card"><h3>Regras simulador</h3><p>Exame desnecessário, conduta incompleta e demora reduzem seu score.</p></div><button class="btn primary" onclick="go('shift')">Iniciar plantão</button></aside></div>`,4)}
function shift(){const c=activeCase();const q=['tempo dos sintomas','histórico familiar','dor em esforço','estresse e sono','sinais de alarme','irradiação da dor','fatores de risco','dor lombar','febre recente','gestação'];app.innerHTML=shell('PLANTÃO - MODO SIMULADOR',`<div class="shift"><aside class="patient-list panel"><h3>Fila de atendimento</h3><b>${patients.length} Pacientes</b>${patients.map((p,i)=>`<div class="patient ${p==c.patient?'active':''}"><span>${String(i+1).padStart(2,'0')}</span><div><b>${p}</b><small>${p==c.patient?'Em atendimento':'Aguardando'}</small></div><time>${['08:15','09:10','09:45','10:20','11:05','11:40','12:22'][i]||'18:'+String(i*5).padStart(2,'0')}</time></div>`).join('')}<button class="btn" onclick="finishCaseCore()">Finalizar consulta</button></aside><section class="case panel"><h2><em>Em atendimento</em>${c.patient}</h2><p>${c.age} anos | ${c.sex}<br>Profissão: ${c.profession}</p><div class="bubble">Doutor(a), estou sentindo ${c.complaint}.</div><img class="patient-art" src="${ui((state.currentCase%3)+1)}"><div class="card vitals"><h3>Sinais vitais</h3>${c.vitals.map(v=>`<div><small>${v[0]}</small><b>${v[1]}</b><small>${v[2]}</small></div>`).join('')}</div><div class="card"><h3>Anamnese dirigida</h3>${q.map(x=>`<button class="listbtn ${selected('questions',x)?'selected':''}" onclick="toggleAction('questions','${x}')">💬 ${x}</button>`).join('')}<input class="input" placeholder="Escreva sua própria pergunta..."></div></section><aside class="rightpanel"><div class="card"><h3>Exames</h3>${exams.map(x=>`<button class="listbtn ${selected('exams',x)?'selected':''}" onclick="toggleAction('exams','${x}')">🧪 ${x}</button>`).join('')}</div><div class="card"><h3>Procedimentos</h3>${procedures.map(x=>`<button class="listbtn ${selected('procedures',x)?'selected':''}" onclick="toggleAction('procedures','${x}')">⚕ ${x}</button>`).join('')}</div><div class="card"><h3>Hipóteses e conduta</h3>${hypotheses.map(x=>`<button class="listbtn ${selected('hypotheses',x)?'selected':''}" onclick="toggleAction('hypotheses','${x}')">${x}</button>`).join('')}<hr>${conducts.map(x=>`<button class="listbtn ${selected('conduct',x)?'selected':''}" onclick="toggleAction('conduct','${x}')">📋 ${x}</button>`).join('')}<button class="btn primary" onclick="finishCaseCore()">Confirmar diagnóstico</button></div></aside></div><div class="hud"><b>Hora clínica ${minToClock()}</b><b>Atendidos ${state.player.patients}</b><b>Criticidade ${state.simulation.criticality}</b><b>Score previsto ${calcScore()}/100</b><button class="btn primary" onclick="toast('Plantão pausado')">Pausar</button></div>`,5)}
function post(){let last=state.completed[state.completed.length-1]||{score:state.score||88,id:'hipertensao-1'},c=cases.find(x=>x.id==last.id)||cases[0],sc=last.score;app.innerHTML=shell('PÓS-CONSULTA',`<section class="post"><div class="card"><h3>Consulta concluída</h3><img class="portrait" src="${ui(2)}"><h2>${c.patient}</h2><p>${c.complaint}</p><div class="success">Diagnóstico final: ${c.diagnosis}</div><p>Reputação atual: <b>${state.player.reputation}</b><br>Sequência: <b>${state.player.streak}</b></p></div><div class="card score"><h2>Sua pontuação</h2><div class="ring">${sc}<small>/100</small></div><h1>${sc>=85?'Muito Bom!':sc>=70?'Bom desempenho':'Revise a conduta'}</h1><p>Score combina anamnese, exames, procedimentos, hipótese, conduta, tempo e excesso de ações.</p><div class="stats"><div>🧠<b>${Math.min(98,sc+2)}%</b><small>Raciocínio</small></div><div>🧪<b>${Math.max(50,sc-3)}%</b><small>Exames</small></div><div>📋<b>${Math.max(55,sc)}%</b><small>Conduta</small></div></div></div><aside class="card"><h3>Linha do tempo</h3>${state.timeline.slice(-8).map(x=>`<p>🕒 ${x.t} — ${x.text}</p>`).join('')||'<p>Consulta registrada.</p>'}<h3>XP e recompensas</h3><p>⭐ +${Math.round(c.xp*(sc/100))} XP<br>💰 +${sc>=80?110:60} Créditos</p><button class="btn primary" onclick="state.actions={questions:[],exams:[],procedures:[],hypotheses:[],conduct:[]};state.timeline=[];go('shift')">Próximo paciente</button><button class="btn" onclick="go('hub')">Voltar ao lobby</button></aside></section>`,7)}
function learning(){app.innerHTML=shell('APRENDIZAGEM MÉDICA',`<div class="layout">${sidebar('learning')}<section class="maincol"><h1>Aprendizagem integrada</h1><div class='card'><h3>Fase 5 ativa</h3><p>Completar módulos melhora missões, XP e domínio clínico.</p></div><div class="procedure card"><img src="${ui(3)}"><div><h2>Cateterismo venoso periférico <small>Básico</small></h2><p>Procedimento para acesso venoso periférico para medicamentos, hidratação ou coleta de exames.</p><p>✅ Indicação • ✅ Materiais • ✅ Técnica segura • ✅ Complicações</p><button class="btn primary" onclick="state.player.learnedModules++;state.player.xp+=60;syncProgress();save();toast('Módulo concluído +60 XP');render()">Marcar como concluído</button></div></div><div class="card"><h3>Todos os procedimentos</h3>${['Coleta de sangue venoso ✅ 100%','Intubação orotraqueal 🟡 60%','Eletrocardiograma (ECG) ✅ 100%','Sutura simples ⚪ 0%','Ultrassonografia POCUS 🟡 20%'].map(x=>`<p>${x}</p>`).join('')}</div></section><aside class="rightcol"><div class="card"><h3>Seu progresso</h3><div class="ring small">${state.player.learnedModules}</div><p>Módulos concluídos</p></div></aside></div>`,9)}
function settings(){app.innerHTML=shell('CONFIGURAÇÕES',`<div class="layout">${sidebar('settings')}<section class="settings-grid"><div class="card"><h2>Geral</h2><p>Idioma: Português (Brasil)<br>Dificuldade: Simulador<br>Salvar automaticamente: Ativo<br>Build: ${BUILD.label}</p><h2>Acessibilidade</h2><p>Legendas: Ativo<br>Alto contraste: Inativo<br>Tamanho do texto: Médio</p></div><div class="card"><h2>Áudio e sistema</h2><label class="toggle"><input type="checkbox" ${state.sound?'checked':''} onchange="state.sound=this.checked;save();toast('Áudio atualizado')"> Sistema de sons</label><p>Micro animações: Ativas<br>Transições: Ativas<br>LocalStorage: ${saveKey}</p><button class="btn primary" onclick="toast('Configurações salvas')">Salvar</button><button class="btn danger" onclick="localStorage.removeItem(saveKey);location.reload()">Resetar progresso local</button></div></section></div>`,10)}
window.pickAvatar=i=>{sound('tap');state.player.avatar=i;save();setup()};window.startGame=()=>{state.player.name=document.querySelector('#name').value||'Dr. Rafael Santos';state.player.short=state.player.name.split(' ').slice(0,2).join(' ');go('menu')};window.go=go;window.state=state;window.toggleDrawer=()=>{state.drawer=!state.drawer;render()};window.toggleAction=toggleAction;window.finishCaseCore=finishCaseCore;window.claimMission=claimMission;function render(){syncProgress();({setup,menu,hub,specialty,shift,post,learning,settings}[state.screen]||setup)()}render();
