const BUILD={version:'0.2.0',stamp:'20260424_1810',label:'v0.2.0 | build 2026-04-24 18:10'};
const A='assets/';
const bg=n=>`${A}backgrounds/background_${String(n).padStart(2,'0')}.png`;
const av=n=>`${A}avatars/avatar_${String(n).padStart(2,'0')}.png`;
const ui=n=>`${A}ui/ui_${String(n).padStart(2,'0')}.png`;
const app=document.querySelector('#app');
const fresh=()=>({screen:'setup',drawer:false,sound:true,player:{name:'Dr. Rafael Santos',short:'Dr. Rafael',avatar:1,level:1,xp:0,credits:2450,reputation:'Boa',days:7,patients:0,correct:88},selectedSpec:'clinica-medica',actions:{questions:[],exams:[],procedures:[],hypotheses:[]},timeline:[],score:null});
let state=JSON.parse(localStorage.getItem('medsim-vale-save-v020')||'null')||fresh();
const save=()=>localStorage.setItem('medsim-vale-save-v020',JSON.stringify(state));
let audioCtx=null;
function sound(type='tap'){ if(!state.sound) return; try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)(); const o=audioCtx.createOscillator(),g=audioCtx.createGain(); o.connect(g); g.connect(audioCtx.destination); const map={tap:[520,.025],ok:[760,.055],warn:[210,.09],nav:[390,.04]}; const [f,d]=map[type]||map.tap; o.frequency.value=f; o.type='sine'; g.gain.setValueAtTime(.0001,audioCtx.currentTime); g.gain.exponentialRampToValueAtTime(.045,audioCtx.currentTime+.01); g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d); o.start(); o.stop(audioCtx.currentTime+d+.01)}catch(e){}}
function go(s){sound('nav'); state.screen=s; state.drawer=false; save(); render();}
function toast(t,type='ok'){sound(type); let e=document.createElement('div'); e.className='toast pop'; e.textContent=t; document.body.append(e); setTimeout(()=>e.remove(),1900)}
const specs=[['cardiologia','Cardiologia','Avalie e trate doenças do coração e sistema circulatório.','❤️',12,bg(4)],['dermatologia','Dermatologia','Diagnostique e trate condições da pele, cabelos e unhas.','🧴',10,bg(5)],['urologia','Urologia','Cuide da saúde do sistema urinário e reprodutor.','🩺',8,bg(6)],['ginecologia','Ginecologia','Acompanhe a saúde da mulher em todas as fases.','♀',10,bg(7)],['urgencia','Urgência e Emergência','Atenda casos críticos e tome decisões que salvam vidas.','✚',15,bg(8)],['clinica-medica','Clínica Médica','Avalie, diagnostique e trate condições clínicas diversas.','⚕',14,bg(9)],['ambulatorio','Ambulatório','Atendimento geral e acompanhamento de rotina.','🏥',9,bg(10)],['pediatria','Pediatria','Cuide da saúde das crianças e adolescentes.','👶',9,bg(11)],['outras','Outras Especialidades','Acesso futuro a novas áreas e especialidades.','+',0,bg(3)]];
const patients=['Carlos Eduardo','Maria Aparecida','João Victor','Fernanda Lima','Luís Fernando','Ana Clara','Marcos Vinícius','Patrícia Gomes','Gabriel Alves','Beatriz Souza','Rafael Moreira','Juliana Costa','Thiago Martins','Ricardo Andrade','Vanessa Oliveira','Mateus Lima','Camila Ferreira','Daniel Rios','Isabela Nunes','André Souza'];
const exams=['Hemograma completo','Eletrocardiograma (ECG)','Raio-X de tórax','Glicemia de jejum','Perfil lipídico','Troponina','Ureia e Creatinina','TSH'];
const procedures=['Aferir sinais vitais','Exame físico geral','Ausculta cardíaca','Ausculta pulmonar','Palpação abdominal','Avaliação neurológica','Solicitar acesso venoso'];
const hypotheses=['Hipertensão Arterial Estágio 1','Angina estável','Ansiedade','Refluxo gastroesofágico','Cefaleia tensional'];
function logo(){return `<div class="brand"><div class="pulse-line"></div><div class="logo"><span>Simulador de</span><b>Medicina</b></div><small>VIVA O PROPÓSITO. SALVE VIDAS.</small></div>`}
function profile(){let p=state.player; return `<div class="profile panel"><img src="${av(p.avatar)}"><div><strong>${p.name}</strong><em>Residente • Nível ${p.level}</em><div class="xp"><i style="width:${Math.min(100,p.xp/(p.level*10))}%"></i></div><small>${p.xp} / ${p.level*1000} XP</small></div></div>`}
function top(section){return `<header class="topbar">${logo()}<button class="hamb" onclick="toggleDrawer()">☰</button><h2>${section}</h2>${profile()}</header>`}
function shell(section,body,bgNum=8){return `<main class="screen fade" style="--bg:url('${bg(bgNum)}')">${top(section)}${body}<div class="build">${BUILD.label}</div></main>`}
function sidebar(active){let items=[['hub','🏠','Lobby','Visão geral'],['learning','📖','Aprendizagem','Procedimentos'],['specialty','🩺','Plantão','Especialidades'],['settings','⚙️','Configurações','Sistema']]; return `<aside class="side panel ${state.drawer?'open':''}">${items.map(x=>`<button onclick="go('${x[0]}')" class="nav ${active==x[0]?'active':''}"><span>${x[1]}</span><b>${x[2]}</b><small>${x[3]}</small></button>`).join('')}</aside><div class="shade ${state.drawer?'show':''}" onclick="toggleDrawer()"></div>`}
function setup(){let avatars=[1,2,3,4,5].map(i=>`<button class="avatar-choice ${state.player.avatar==i?'active':''}" onclick="pickAvatar(${i})"><img src="${av(i)}"></button>`).join(''); app.innerHTML=`<main class="screen fade" style="--bg:url('${bg(1)}')">${logo()}<img class="hero-doc" src="${av(state.player.avatar)}"><section class="setup panel pop"><h3>🫀 NOVO GAME</h3><h2>1. Escolha seu avatar</h2><div class="avatar-row">${avatars}</div><h2>2. Nome do personagem</h2><input class="input" id="name" value="${state.player.name}" placeholder="Digite seu nome"><h2>3. País de origem</h2><select class="input"><option>🇧🇷 Brasil</option><option>Portugal</option><option>Angola</option></select><button class="btn primary" onclick="startGame()">🫀 Continuar</button></section><button class="btn ghost back" onclick="go('menu')">Voltar</button><div class="build">${BUILD.label}</div></main>`}
function menu(){app.innerHTML=`<main class="screen fade" style="--bg:url('${bg(2)}')">${logo()}<section class="welcome slide"><h1>Bem-vindo,<br><span>${state.player.short}</span></h1><p>O conhecimento é a sua maior ferramenta. Cada decisão pode mudar uma vida.</p></section><section class="mode-grid"><article class="mode card" style="--cardbg:url('${bg(3)}')"><h2>Modo Carreira</h2><p>Construa sua carreira do zero. Aprenda, evolua, especialize-se e torne-se referência.</p><button class="btn primary" onclick="go('hub')">Entrar</button></article><article class="mode card" style="--cardbg:url('${bg(7)}')"><h2>Modo Livre <span>Sandbox</span></h2><p>Pratique e experimente procedimentos sem pressão.</p><button class="btn" onclick="go('specialty')">Praticar</button></article></section><div class="build">${BUILD.label}</div></main>`}
function hub(){let p=state.player; app.innerHTML=shell('LOBBY DO RESIDENTE',`<div class="layout">${sidebar('hub')}<section class="maincol"><div class="hero-card card" style="--cardbg:url('${bg(8)}')"><h1>Bem-vinda, ${p.name.includes('Ana')?'Dra. Ana Laura':'Doutor(a) Residente'}!</h1><p>Continue assim. Cada vida importa!</p><div class="level medallion">1</div><div class="stats"><div>🏆<b>1.250</b><small>Pontos</small></div><div>🌐<b>#1.248</b><small>Ranking</small></div><div>👥<b>${p.patients}</b><small>Pacientes</small></div><div>🎯<b>${p.correct}%</b><small>Acerto</small></div></div></div><div class="two"><div class="card"><h3>Progresso da carreira</h3><p>Residência em Clínica Médica — R1</p><div class="xp big"><i style="width:65%"></i></div><button class="btn primary" onclick="go('specialty')">Iniciar plantão</button></div><div class="card"><h3>Casos recentes</h3><p>✅ Hipertensão Arterial <b>+120 XP</b></p><p>✅ Cefaleia Tensional <b>+100 XP</b></p><p>⚠️ Dermatite Atópica <b>+60 XP</b></p></div></div></section><aside class="rightcol"><div class="card"><h3>Promoções e recompensas</h3><h2>Residente Sênior</h2><div class="xp big"><i style="width:33%"></i></div><p>650 / 2000 XP</p></div><div class="card"><h3>Missões diárias</h3><p>✅ Atender 5 pacientes <b>5/5</b></p><p>🧪 Solicitar 3 exames <b>2/3</b></p><p>📋 Diagnosticar 2 casos difíceis <b>1/2</b></p></div><button class="btn danger" onclick="go('menu')">Encerrar turno</button></aside></div>`,8)}
function specialty(){app.innerHTML=shell('PLANTÃO — ESPECIALIDADE',`<div class="layout">${sidebar('specialty')}<section class="maincol"><h1>Escolha sua especialidade</h1><p class="muted">Cada especialidade traz desafios únicos.</p><div class="specialties">${specs.map(s=>`<article class="spec card" onclick="state.selectedSpec='${s[0]}';go('shift')"><img src="${s[5]}"><span>${s[3]}</span><h2>${s[1]}</h2><p>${s[2]}</p><b>Pacientes ${s[4]||'Em breve'}</b></article>`).join('')}</div><div class="info card">⏱ Duração 12 horas • 👥 Equipe variável • 📋 Dificuldade normal</div></section><aside class="rightcol"><div class="card"><h3>Dica</h3><p>Escolha a especialidade que mais combina com seus objetivos.</p></div><button class="btn primary" onclick="go('shift')">Iniciar plantão</button></aside></div>`,4)}
function shift(){app.innerHTML=shell('PLANTÃO - CLÍNICA MÉDICA',`<div class="shift"><aside class="patient-list panel"><h3>Fila de atendimento</h3><b>20 Pacientes</b>${patients.map((p,i)=>`<div class="patient ${i==6?'active':''}"><span>${String(i+1).padStart(2,'0')}</span><div><b>${p}</b><small>${i==6?'Em atendimento':'Aguardando'}</small></div><time>${['08:15','09:10','09:45','10:20','11:05','11:40','12:22'][i]||'18:'+String(i*5).padStart(2,'0')}</time></div>`).join('')}<button class="btn" onclick="go('post')">Encerrar plantão</button></aside><section class="case panel"><h2><em>Em atendimento</em>Marcos Vinícius</h2><p>♂ 34 anos | Masculino<br>Profissão: Analista de Sistemas</p><button class="btn mini">Ver histórico</button><div class="bubble">Doutor(a), estou sentindo dores de cabeça frequentes, cansaço e um aperto no peito às vezes.</div><img class="patient-art" src="${ui(1)}"><div class="card vitals"><h3>Sinais vitais</h3>${[['PA','128/82','mmHg'],['FC','88','bpm'],['FR','18','irpm'],['TEMP.','36,7','°C'],['SpO₂','98','%']].map(v=>`<div><small>${v[0]}</small><b>${v[1]}</b><small>${v[2]}</small></div>`).join('')}</div><div class="card"><h3>Perguntas que você pode fazer</h3>${['Há quanto tempo os sintomas começaram?','Sente palpitações ou batimentos acelerados?','A dor acontece em repouso ou esforço?','Tem histórico de pressão alta ou diabetes?','Faz uso de algum medicamento?'].map(q=>`<button class="listbtn ${state.actions.questions.includes(q)?'selected':''}" onclick="toggle('questions','${q}')">💬 ${q}</button>`).join('')}</div></section><aside class="rightpanel"><div class="card"><h3>Exames disponíveis</h3>${exams.map(x=>`<button class="listbtn ${state.actions.exams.includes(x)?'selected':''}" onclick="toggle('exams','${x}')">${x}</button>`).join('')}</div><div class="card"><h3>Procedimentos</h3>${procedures.map(x=>`<button class="listbtn ${state.actions.procedures.includes(x)?'selected':''}" onclick="toggle('procedures','${x}')">${x}</button>`).join('')}</div><div class="card"><h3>Hipóteses diagnósticas</h3>${hypotheses.map(x=>`<button class="listbtn ${state.actions.hypotheses.includes(x)?'selected':''}" onclick="toggle('hypotheses','${x}')">${x}</button>`).join('')}<button class="btn primary" onclick="finishCase()">Finalizar consulta</button></div></aside></div><footer class="hud"><span>👥 Atendidos 6</span><span>🩺 Em atendimento 1</span><span>⏱ 07:35:20</span><button class="btn mini" onclick="toast('Plantão pausado')">Pausar plantão</button></footer>`,5)}
function post(){let sc=state.score||88; app.innerHTML=shell('PÓS-CONSULTA',`<section class="post"><div class="card"><h3>Consulta concluída</h3><img class="portrait" src="${ui(2)}"><h2>Marcos Vinícius</h2><p>Queixa principal: dores de cabeça frequentes, cansaço e aperto no peito.</p><div class="success">Diagnóstico final: Hipertensão Arterial Estágio 1</div><p>✅ ECG solicitado<br>✅ Orientação de estilo de vida<br>✅ Retorno em 30 dias</p></div><div class="card score"><h2>Sua pontuação</h2><div class="ring">${sc}<small>/100</small></div><h1>${sc>=85?'Muito Bom!':'Bom trabalho!'}</h1><p>Você conduziu o caso com segurança e raciocínio clínico eficiente.</p><div class="stats"><div>🧠<b>90%</b><small>Raciocínio</small></div><div>🧪<b>85%</b><small>Exames</small></div><div>📋<b>88%</b><small>Conduta</small></div></div></div><aside class="card"><h3>Desempenho geral</h3><p>✅ Acertos 23 — 76%</p><p>⚠️ Parciais 5 — 17%</p><p>❌ Erros 2 — 7%</p><h3>XP e recompensas</h3><p>⭐ +120 XP<br>💰 +50 Créditos<br>🏆 Conquista desbloqueada</p><button class="btn primary" onclick="state.player.xp+=120;state.player.patients+=1;go('hub')">Continuar plantão</button></aside></section>`,7)}
function learning(){app.innerHTML=shell('APRENDIZAGEM MÉDICA',`<div class="layout">${sidebar('learning')}<section class="maincol"><h1>Procedimentos e conhecimentos</h1><div class="procedure card"><img src="${ui(3)}"><div><h2>Cateterismo venoso periférico <small>Básico</small></h2><p>Procedimento para acesso venoso periférico para medicamentos, hidratação ou coleta de exames.</p><p>✅ Indicar corretamente<br>✅ Conhecer materiais<br>✅ Técnica segura<br>✅ Manejar complicações</p><button class="btn primary" onclick="toast('Procedimento concluído')">Marcar como concluído</button></div></div><div class="card"><h3>Todos os procedimentos</h3>${['Coleta de sangue venoso ✅ 100%','Intubação orotraqueal 🟡 60%','Eletrocardiograma (ECG) ✅ 100%','Sutura simples ⚪ 0%','Ultrassonografia POCUS 🟡 20%'].map(x=>`<p>${x}</p>`).join('')}</div></section><aside class="rightcol"><div class="card"><h3>Seu progresso</h3><div class="ring small">42%</div><p>Concluídos 18<br>Em andamento 12<br>Não iniciados 15</p></div></aside></div>`,9)}
function settings(){app.innerHTML=shell('CONFIGURAÇÕES',`<div class="layout">${sidebar('settings')}<section class="settings-grid"><div class="card"><h2>Geral</h2>${['Idioma: Português (Brasil)','Dificuldade: Normal','Dicas durante o jogo: Ativo','Salvar automaticamente: Ativo','Modo tela cheia: Ativo'].map(x=>`<p>${x}</p>`).join('')}<h2>Acessibilidade</h2><p>Legendas: Ativo<br>Alto contraste: Inativo<br>Tamanho do texto: Médio</p></div><div class="card"><h2>Gráficos</h2><p>Qualidade: Alto<br>Resolução: Responsiva<br>Sombras: Alto<br>Taxa de quadros: Ilimitado</p><h2>Áudio</h2><label class="toggle"><input type="checkbox" ${state.sound?'checked':''} onchange="state.sound=this.checked;save();toast('Áudio atualizado')"> Sistema de sons</label><p>Volume geral 80%<br>Efeitos sonoros 75%<br>Música de fundo 40%</p><button class="btn primary" onclick="toast('Configurações salvas')">Salvar e aplicar</button></div></section></div>`,10)}
window.pickAvatar=i=>{sound('tap');state.player.avatar=i;save();setup()};
window.startGame=()=>{state.player.name=document.querySelector('#name').value||'Dr. Rafael Santos';state.player.short=state.player.name.split(' ').slice(0,2).join(' ');go('menu')};
window.go=go; window.state=state; window.toggleDrawer=()=>{state.drawer=!state.drawer;render()};
window.toggle=(k,v)=>{let a=state.actions[k]; a.includes(v)?a.splice(a.indexOf(v),1):a.push(v); state.timeline.push(v); save(); toast('Ação registrada')};
window.finishCase=()=>{let good=['Eletrocardiograma (ECG)','Perfil lipídico','Aferir sinais vitais','Exame físico geral','Hipertensão Arterial Estágio 1'];let flat=[...state.actions.exams,...state.actions.procedures,...state.actions.hypotheses];state.score=Math.min(100,70+good.filter(x=>flat.includes(x)).length*6);save();go('post')};
function render(){({setup,menu,hub,specialty,shift,post,learning,settings}[state.screen]||setup)()} render();
